LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := .su
LOCAL_SRC_FILES := SuperSU/arm/su
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT)/xbin
LOCAL_UNSTRIPPED_PATH :=
LOCAL_POST_INSTALL_CMD := chmod 0755 $(LOCAL_MODULE_PATH)/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := su
LOCAL_SRC_FILES := SuperSU/arm/su
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin/.ext
LOCAL_UNSTRIPPED_PATH :=
LOCAL_POST_INSTALL_CMD := chmod 0777 $(LOCAL_MODULE_PATH) && chmod 0755 $(LOCAL_MODULE_PATH)/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

